### PR TITLE
2.0 is always enabled now

### PR DESCRIPTION
**Pull request by schmidtl**
is this flag (newApplicationModelEnabled) even needed anymore ?

### CODE REVIEW

**Comment by codepitbull** [comment]
Stupid question, but was the current state where app 2.0 was optional a state where this version was still usable for on-prem?

**Comment by codepitbull** [comment]
We clarified that:
a) It won't have impact on users of older versions
b) Next version of the plugin will be bumped to 2.0.0

**Comment by schmidtl** [comment]
Reverted, to build&release another version upfront, with less changes than for upcoming 2.0.0

**Comment by schmidtl** [comment]
new pr will come

**Pull request merged**
